server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://room5-ecommer.crwgy8emwlhz.us-east-2.rds.amazonaws.com:3306/demo
    username: admin
    password: Revature_room5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
